branch-defaults:
  default:
    environment: null
    group_suffix: null
  production:
    environment: Management
global:
  application_name: Management
  branch: null
  default_ec2_keyname: management
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
